services:
  app:
    build:
      context: .
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: assistant_bot
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      TELEGRAM_BOT_TOKEN: "7561371537:AAFLPtU6YV20uWGdz1HKJWY5vnwYGLqHLTc"
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: assistant_bot
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
