name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          extensions: mbstring, bcmath, xml, tokenizer, ctype, json
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            mysqladmin ping -h127.0.0.1 -uroot -ppassword && break
            echo 'Waiting for MySQL...'
            sleep 1
          done

      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing_db
          DB_USERNAME: root
          DB_PASSWORD: password
        run: php artisan migrate --env=testing --force

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing_db
          DB_USERNAME: root
          DB_PASSWORD: password
        run: php artisan test --no-interaction --env=testing

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: ssh -o StrictHostKeyChecking=no deploy@95.163.231.194 'bash /var/www/deploy.sh'
