name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          extensions: mbstring, bcmath, xml, tokenizer, ctype, json
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - run: composer install --no-progress --prefer-dist --optimize-autoloader

      - run: php artisan test --no-interaction --env=testing

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: ssh -o StrictHostKeyChecking=no deploy@95.163.231.194 'bash /var/www/deploy.sh'
